### ISSUE TITLE
Images are not correctly sizes.

### ISSUE THREAD

**Issue by esegally** [sean111/terrariahb#18]
Very minor issue, but you need to polish up the images. They are squashed and not correctly sized. Just a minor issue, that it fixed would make this app so much better.

**Comment by sean111** [comment]
Sadly due to app size restrictions on many 2.x devices I don't make thumbnail images to use in the nav. I am currently working on a completely new version of the app and plan to try to make it smart scale them. It drives me nuts too but had to cut the corner to use them lol.

**Comment by sean111** [comment]
Closing this out as the app is no longer available.
