### ISSUE TITLE
Update too 1.2

### ISSUE THREAD

**Issue by ArranCrowley** [sean111/terrariahb#19]
Plzz update your app to 1.2 its annoying that i cant look ip to bosses and armour like plantera if you have done this you have the best terraria wiki app out there

**Comment by sean111** [comment]
Due to work and other things the app has taken a backseat, especially since it's free and I'm the only one working on it :p. I am looking into ways to go about re-doing the application to be faster and take up less space. However I do not have an ETA on this yet.

**Comment by sean111** [comment]
Closing this out since the app is no longer available.
